"""Added Unique Indexes

Revision ID: 4119d78cc001
Revises: 65d0d3bd6a0f
Create Date: 2025-04-10 15:11:34.227326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4119d78cc001'
down_revision = '65d0d3bd6a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_alumno', ['legajo', 'persona_id'])

    with op.batch_alter_table('alumno_comision', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_alumno_comision', ['comision_id', 'alumno_id'])

    with op.batch_alter_table('carrera', schema=None) as batch_op:
        batch_op.drop_index('ix_carrera_nombre')
        batch_op.create_index(batch_op.f('ix_carrera_nombre'), ['nombre'], unique=False)
        batch_op.create_unique_constraint('uix_carrera_institucion', ['institucion_id', 'nombre'])

    with op.batch_alter_table('comision', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_comision', ['ciclolectivo_id', 'cuatrimestre_id', 'turno_id', 'materiadocente_id'])

    with op.batch_alter_table('cuatrimestre', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_cuatrimestre_ciclo', ['ciclolectivo_id', 'nombre'])

    with op.batch_alter_table('materia_docente', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_materia_docente', ['docente_id', 'materiaplan_id'])

    with op.batch_alter_table('materia_plan', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_materia_plan', ['planestudio_id', 'materia_id', 'anio_id'])

    with op.batch_alter_table('plan_estudio', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_plan_carrera', ['carrera_id', 'nombre'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_estudio', schema=None) as batch_op:
        batch_op.drop_constraint('uix_plan_carrera', type_='unique')

    with op.batch_alter_table('materia_plan', schema=None) as batch_op:
        batch_op.drop_constraint('uix_materia_plan', type_='unique')

    with op.batch_alter_table('materia_docente', schema=None) as batch_op:
        batch_op.drop_constraint('uix_materia_docente', type_='unique')

    with op.batch_alter_table('cuatrimestre', schema=None) as batch_op:
        batch_op.drop_constraint('uix_cuatrimestre_ciclo', type_='unique')

    with op.batch_alter_table('comision', schema=None) as batch_op:
        batch_op.drop_constraint('uix_comision', type_='unique')

    with op.batch_alter_table('carrera', schema=None) as batch_op:
        batch_op.drop_constraint('uix_carrera_institucion', type_='unique')
        batch_op.drop_index(batch_op.f('ix_carrera_nombre'))
        batch_op.create_index('ix_carrera_nombre', ['nombre'], unique=1)

    with op.batch_alter_table('alumno_comision', schema=None) as batch_op:
        batch_op.drop_constraint('uix_alumno_comision', type_='unique')

    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.drop_constraint('uix_alumno', type_='unique')

    # ### end Alembic commands ###
