"""Inicio

Revision ID: 65d0d3bd6a0f
Revises: 
Create Date: 2025-04-09 22:44:45.962765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65d0d3bd6a0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anio_numero'), ['numero'], unique=True)

    op.create_table('cargo_docente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cargo_docente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cargo_docente_nombre'), ['nombre'], unique=False)

    op.create_table('ciclo_lectivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('finicio', sa.DateTime(), nullable=False),
    sa.Column('ffin', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ciclo_lectivo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ciclo_lectivo_anio'), ['anio'], unique=True)

    op.create_table('institucion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=256), nullable=False),
    sa.Column('domicilio', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institucion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institucion_nombre'), ['nombre'], unique=True)

    op.create_table('materia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materia_nombre'), ['nombre'], unique=True)

    op.create_table('persona',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apellido', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('fnacto', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persona_apellido'), ['apellido'], unique=False)
        batch_op.create_index(batch_op.f('ix_persona_dni'), ['dni'], unique=True)
        batch_op.create_index(batch_op.f('ix_persona_nombre'), ['nombre'], unique=False)

    op.create_table('tipo_contacto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('turno',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turno_nombre'), ['nombre'], unique=True)

    op.create_table('alumno',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('fingreso', sa.DateTime(), nullable=False),
    sa.Column('fegreso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrera',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('anios', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institucion_id'], ['institucion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carrera', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carrera_nombre'), ['nombre'], unique=True)

    op.create_table('contacto_persona',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('tipocontacto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.ForeignKeyConstraint(['tipocontacto_id'], ['tipo_contacto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuatrimestre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('ciclolectivo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ciclolectivo_id'], ['ciclo_lectivo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cuatrimestre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cuatrimestre_nombre'), ['nombre'], unique=True)

    op.create_table('docente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('legajo', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['persona.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_nombre'), ['nombre'], unique=True)

    op.create_table('docente_cargo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('cargodocente_id', sa.Integer(), nullable=False),
    sa.Column('finicio', sa.DateTime(), nullable=False),
    sa.Column('ffin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cargodocente_id'], ['cargo_docente.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_estudio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('finicio', sa.DateTime(), nullable=True),
    sa.Column('ffin', sa.DateTime(), nullable=True),
    sa.Column('carrera_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrera_id'], ['carrera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_estudio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_estudio_nombre'), ['nombre'], unique=True)

    op.create_table('posteo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('texto', sa.String(length=140), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posteo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posteo_fecha'), ['fecha'], unique=False)

    op.create_table('materia_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('planestudio_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('anio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anio_id'], ['anio.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], ),
    sa.ForeignKeyConstraint(['planestudio_id'], ['plan_estudio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materia_docente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('materiaplan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['docente_id'], ['docente.id'], ),
    sa.ForeignKeyConstraint(['materiaplan_id'], ['materia_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ciclolectivo_id', sa.Integer(), nullable=False),
    sa.Column('cuatrimestre_id', sa.Integer(), nullable=False),
    sa.Column('turno_id', sa.Integer(), nullable=False),
    sa.Column('materiadocente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ciclolectivo_id'], ['ciclo_lectivo.id'], ),
    sa.ForeignKeyConstraint(['cuatrimestre_id'], ['cuatrimestre.id'], ),
    sa.ForeignKeyConstraint(['materiadocente_id'], ['materia_docente.id'], ),
    sa.ForeignKeyConstraint(['turno_id'], ['turno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumno_comision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comision_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['comision_id'], ['comision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alumno_comision')
    op.drop_table('comision')
    op.drop_table('materia_docente')
    op.drop_table('materia_plan')
    with op.batch_alter_table('posteo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posteo_fecha'))

    op.drop_table('posteo')
    with op.batch_alter_table('plan_estudio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_estudio_nombre'))

    op.drop_table('plan_estudio')
    op.drop_table('docente_cargo')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_nombre'))

    op.drop_table('usuario')
    op.drop_table('docente')
    with op.batch_alter_table('cuatrimestre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cuatrimestre_nombre'))

    op.drop_table('cuatrimestre')
    op.drop_table('contacto_persona')
    with op.batch_alter_table('carrera', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carrera_nombre'))

    op.drop_table('carrera')
    op.drop_table('alumno')
    with op.batch_alter_table('turno', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turno_nombre'))

    op.drop_table('turno')
    op.drop_table('tipo_contacto')
    with op.batch_alter_table('persona', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persona_nombre'))
        batch_op.drop_index(batch_op.f('ix_persona_dni'))
        batch_op.drop_index(batch_op.f('ix_persona_apellido'))

    op.drop_table('persona')
    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materia_nombre'))

    op.drop_table('materia')
    with op.batch_alter_table('institucion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institucion_nombre'))

    op.drop_table('institucion')
    with op.batch_alter_table('ciclo_lectivo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ciclo_lectivo_anio'))

    op.drop_table('ciclo_lectivo')
    with op.batch_alter_table('cargo_docente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cargo_docente_nombre'))

    op.drop_table('cargo_docente')
    with op.batch_alter_table('anio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anio_numero'))

    op.drop_table('anio')
    # ### end Alembic commands ###
